[package]
name = "tauri-plugin-constellation-android"
version = "0.1.1-rc.1"
edition = "2021"
license = "MIT"
links = "tauri-plugin-constellation-android"

[dependencies]
serde = "1"
serde_json = "1"
tauri = "=2.11.5"
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
